Fix broken Electron installation for react-devtools
When doing "pnpm run-with-devtools", the following error logs would appear:

[WARN] Unsupported engine: wanted: {"node":"24.15.0"} (current: {"node":"v22.22.2","pnpm":"11.5.2"})
$ cross-env REACT_DEVTOOLS=1 run-p --print-label react-devtools start
[start         ] [WARN] Unsupported engine: wanted: {"node":"24.15.0"} (current: {"node":"v22.22.2","pnpm":"11.5.2"})
[react-devtools] [WARN] Unsupported engine: wanted: {"node":"24.15.0"} (current: {"node":"v22.22.2","pnpm":"11.5.2"})
[start         ] $ electron .
[react-devtools] $ react-devtools
[react-devtools] /home/user/Projects/Signal-Desktop/node_modules/.pnpm/electron@23.3.13/node_modules/electron/index.js:17
[react-devtools]     throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again');
[react-devtools]     ^
[react-devtools]
[react-devtools] Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
[react-devtools]     at getElectronPath (/home/user/Projects/Signal-Desktop/node_modules/.pnpm/electron@23.3.13/node_modules/electron/index.js:17:11)
[react-devtools]     at Object.<anonymous> (/home/user/Projects/Signal-Desktop/node_modules/.pnpm/electron@23.3.13/node_modules/electron/index.js:21:18)
[react-devtools]     at Module._compile (node:internal/modules/cjs/loader:1705:14)
[react-devtools]     at Module._extensions..js (node:internal/modules/cjs/loader:1838:10)
[react-devtools]     at Module.load (node:internal/modules/cjs/loader:1441:32)
[react-devtools]     at Module._load (node:internal/modules/cjs/loader:1263:12)
[react-devtools]     at TracingChannel.traceSync (node:diagnostics_channel:328:14)
[react-devtools]     at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
[react-devtools]     at Module.require (node:internal/modules/cjs/loader:1463:12)
[react-devtools]     at require (node:internal/modules/helpers:147:16)
[react-devtools]
[react-devtools] Node.js v22.22.2
[react-devtools] [ELIFECYCLE] Command failed with exit code 1.
[start         ] /home/user/Projects/Signal-Desktop/node_modules/.pnpm/electron@42.3.0/node_modules/electron/dist/electron exited with signal SIGTERM
[start         ] [ELIFECYCLE] Command failed with exit code 1.
ERROR: "react-devtools" exited with 1.
[ELIFECYCLE] Command failed with exit code 1.

It seems that pnpm disables post-install scripts by default, breaking Electron.
While they have already been re-enabled for Electron 42.3.0 used by Signal
Desktop itself, react-devtools uses a different version, 23.3.13. Also enable
post-install scripts for Electron 23.3.13. This makes react-devtools work.

This was helped by https://github.com/react/react/issues/35389.